spring:
  application:
    name: order

  datasource:
    url: jdbc:mysql://localhost:3307/springcloud_sell?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

eureka:
  client:
    serviceurl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

env:
  dev
